feature(RE-1033): Add projects and update group to projects.
VibrentHealth/harbor-helm pull request #1
Opened 2020-07-14 05:20 UTC by vinayp-vignet

RE-1033. 
This PR contains, 
1. configMap and Job to add the projects to harbor 
2. values.yaml project and group relationship structure.

2020-07-14 18:03 UTC, agill17 requested changes

2020-07-14 18:03 UTC, agill17 commented on templates/custom/harbor-job.yaml
> +        image: harbor-helper:3.0
parameterize this. So that in case we find vulnerabilities during runtime we can swap out to diff image vs having to update the chart

2020-07-14 18:03 UTC, agill17 commented on templates/custom/harbor-job.yaml
> +    spec:
add imagePullSecrets incase we decide to swap to our custom image. 
```
      {{- if .job.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .job.imagePullSecrets | indent 6 }}
      {{- end }}
```

2020-07-21 16:26 UTC, vinayp-vignet commented
Closing this PR. 
Not relevant.

2020-07-21 16:26 UTC, closed without merging